name: 'build'

on:
  push:
    branches:
    - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v3.1.0
        with:
          registry: ghcr.io
          username: florentinl
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: florentinl/oauth2-middleware
          tags: latest
